### ISSUE TITLE
Error deleting VM (plain `exit status 1`)

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/bosh-warden-cpi-release#12]
Tried to delete the deployment, got this error:

```
Error: CPI error 'Bosh::Clouds::CloudError' with message 'Deleting vm '{{1d178d46-ad2e-449d-662b-d0965906cc3e}}': exit status 1' in 'delete_vm' CPI method
```

We've seen this multiple times in CI. Using warden CPI version 37.

Debug logs attached.
[warden-debug.log](https://github.com/cppforlife/bosh-warden-cpi-release/files/1391836/warden-debug.log)

**Comment by ljfranklin** [comment]
@cppforlife we see this several times a week in our CI. Any ideas why this might be happening?

**Comment by cppforlife** [comment]
@tcdowney @ljfranklin hmm, not sure, you still have an env?

**Comment by anniesing** [comment]
@cppforlife This happened again yesterday. I have the env if you want to look at it or have specific logs you want me to look for.

**Comment by bgandon** [comment]
Is this still valid?

**Comment by bgandon** [comment]
All right, let's close this. Thanks!
